#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Dynastream Innovations Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2016 Dynastream Innovations Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 16.60Release
// Tag = production-akw-16.60.00-0-g5d3d436
////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dynastream.Fit
{
    /// <summary>
    /// Implements the profile SportBits3 type as a class
    /// </summary>
    public static class SportBits3 
    {
        public const byte Driving = 0x01;
        public const byte Golf = 0x02;
        public const byte HangGliding = 0x04;
        public const byte HorsebackRiding = 0x08;
        public const byte Hunting = 0x10;
        public const byte Fishing = 0x20;
        public const byte InlineSkating = 0x40;
        public const byte RockClimbing = 0x80;
        public const byte Invalid = (byte)0x00;
        
    }
}

